# Generated by Django 2.0.4 on 2018-04-18 15:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LSTSData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lsts_id', models.CharField(max_length=88)),
                ('country_of_origin', models.CharField(max_length=128)),
                ('food', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Sample',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seqid', models.CharField(max_length=56)),
            ],
        ),
        migrations.CreateModel(
            name='SeqData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('n50', models.IntegerField()),
                ('num_contigs', models.IntegerField()),
                ('rmlst', models.CharField(max_length=56)),
                ('date_sequenced', models.DateField()),
                ('seqid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seqdata', to='data_wrapper.Sample')),
            ],
        ),
        migrations.AddField(
            model_name='lstsdata',
            name='seqid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lsts_data', to='data_wrapper.Sample'),
        ),
    ]
