# Generated by Django 2.0.4 on 2018-04-20 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_wrapper', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seqdata',
            name='date_sequenced',
            field=models.DateTimeField(),
        ),
    ]
