# Generated by Django 2.0.4 on 2018-05-09 18:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data_wrapper', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resfinderdata',
            name='seqid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resfinder_data', to='data_wrapper.SeqData'),
        ),
    ]
