# Generated by Django 2.0.4 on 2018-05-10 13:24

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_wrapper', '0002_auto_20180509_1839'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seqidlist',
            name='seqid_list',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=256), size=None),
        ),
    ]
