# Generated by Django 2.0.4 on 2018-04-26 19:04

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_wrapper', '0003_savedtables'),
    ]

    operations = [
        migrations.CreateModel(
            name='SeqIdList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seqid_list', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=48), size=None)),
            ],
        ),
    ]
