# Generated by Django 2.0.4 on 2018-05-10 14:14

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_wrapper', '0004_lstsidlist_olnidlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='culturedata',
            name='concentration',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='culturedata',
            name='discard_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='culturedata',
            name='gdna_extracted_by',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='culturedata',
            name='gdna_extraction_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='culturedata',
            name='gdna_extraction_method',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='culturedata',
            name='quantification_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='culturedata',
            name='quantification_method',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='culturedata',
            name='quantified_by',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='culturedata',
            name='received_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historicalculturedata',
            name='concentration',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historicalculturedata',
            name='discard_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historicalculturedata',
            name='gdna_extracted_by',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='historicalculturedata',
            name='gdna_extraction_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historicalculturedata',
            name='gdna_extraction_method',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='historicalculturedata',
            name='quantification_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historicalculturedata',
            name='quantification_method',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='historicalculturedata',
            name='quantified_by',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='historicalculturedata',
            name='received_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historicallstsdata',
            name='country_of_origin',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='historicallstsdata',
            name='food',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='historicaloln',
            name='extra_lsts_data',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='historicaloln',
            name='oln_genus',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='historicaloln',
            name='oln_id',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='historicaloln',
            name='oln_serotype',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='historicaloln',
            name='oln_source',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='historicaloln',
            name='oln_species',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='historicaloln',
            name='oln_subspecies',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='historicaloln',
            name='oln_verotoxin',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='historicaloln',
            name='oneenzyme',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='historicaloln',
            name='other_id',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='historicaloln',
            name='twoenzyme',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='historicalresfinderdata',
            name='resfinder_aa_identity',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='historicalresfinderdata',
            name='resfinder_allele',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historicalresfinderdata',
            name='resfinder_contig',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='historicalresfinderdata',
            name='resfinder_gene',
            field=models.CharField(blank=True, max_length=56, null=True),
        ),
        migrations.AlterField(
            model_name='historicalresfinderdata',
            name='resfinder_location',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='historicalresfinderdata',
            name='resfinder_percent_covered',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historicalresfinderdata',
            name='resfinder_percent_identity',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historicalresfinderdata',
            name='resfinder_resistance',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='historicalresfinderdata',
            name='resfinder_sequence',
            field=models.CharField(blank=True, max_length=8192, null=True),
        ),
        migrations.AlterField(
            model_name='historicalseqdata',
            name='amr_profile',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='historicalseqdata',
            name='amr_resistant',
            field=models.CharField(blank=True, max_length=56, null=True),
        ),
        migrations.AlterField(
            model_name='historicalseqdata',
            name='analyst',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='historicalseqdata',
            name='assembly_quality',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='historicalseqdata',
            name='average_coverage_depth',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historicalseqdata',
            name='core_genes_present',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='historicalseqdata',
            name='coverage_depth_std',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historicalseqdata',
            name='date_assembled',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historicalseqdata',
            name='ecoli_serotype',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='historicalseqdata',
            name='error_rate',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historicalseqdata',
            name='flowcell',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='historicalseqdata',
            name='geneseekr_profile',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='historicalseqdata',
            name='genus',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='historicalseqdata',
            name='insert_size_std',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historicalseqdata',
            name='length_forward_read',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historicalseqdata',
            name='length_reverse_read',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historicalseqdata',
            name='machine_name',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='historicalseqdata',
            name='mash_num_matching_hashes',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='historicalseqdata',
            name='mash_reference_genome',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='historicalseqdata',
            name='mean_insert_size',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historicalseqdata',
            name='mlst',
            field=models.CharField(blank=True, max_length=56, null=True),
        ),
        migrations.AlterField(
            model_name='historicalseqdata',
            name='mlst_allele_1',
            field=models.CharField(blank=True, max_length=56, null=True),
        ),
        migrations.AlterField(
            model_name='historicalseqdata',
            name='mlst_allele_2',
            field=models.CharField(blank=True, max_length=56, null=True),
        ),
        migrations.AlterField(
            model_name='historicalseqdata',
            name='mlst_allele_3',
            field=models.CharField(blank=True, max_length=56, null=True),
        ),
        migrations.AlterField(
            model_name='historicalseqdata',
            name='mlst_allele_4',
            field=models.CharField(blank=True, max_length=56, null=True),
        ),
        migrations.AlterField(
            model_name='historicalseqdata',
            name='mlst_allele_5',
            field=models.CharField(blank=True, max_length=56, null=True),
        ),
        migrations.AlterField(
            model_name='historicalseqdata',
            name='mlst_allele_6',
            field=models.CharField(blank=True, max_length=56, null=True),
        ),
        migrations.AlterField(
            model_name='historicalseqdata',
            name='mlst_allele_7',
            field=models.CharField(blank=True, max_length=56, null=True),
        ),
        migrations.AlterField(
            model_name='historicalseqdata',
            name='n50',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historicalseqdata',
            name='num_clusters_pf',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historicalseqdata',
            name='num_contigs',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historicalseqdata',
            name='percent_gc',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historicalseqdata',
            name='percent_reads_phix',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historicalseqdata',
            name='pipeline_version',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='historicalseqdata',
            name='plasmid_profile',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='historicalseqdata',
            name='predicted_genes_over_1000',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historicalseqdata',
            name='predicted_genes_over_3000',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historicalseqdata',
            name='predicted_genes_over_500',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historicalseqdata',
            name='predicted_genes_under_500',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historicalseqdata',
            name='real_time_strain',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='historicalseqdata',
            name='rmlst',
            field=models.CharField(blank=True, max_length=56, null=True),
        ),
        migrations.AlterField(
            model_name='historicalseqdata',
            name='sample_purity',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='historicalseqdata',
            name='seqid',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='historicalseqdata',
            name='sequencing_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historicalseqdata',
            name='sistr_serovar_antigen',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='historicalseqdata',
            name='sistr_serovar_cgmlst',
            field=models.CharField(blank=True, max_length=56, null=True),
        ),
        migrations.AlterField(
            model_name='historicalseqdata',
            name='sistr_serovar_h1',
            field=models.CharField(blank=True, max_length=56, null=True),
        ),
        migrations.AlterField(
            model_name='historicalseqdata',
            name='sistr_serovar_h2',
            field=models.CharField(blank=True, max_length=56, null=True),
        ),
        migrations.AlterField(
            model_name='historicalseqdata',
            name='sistr_serovar_serogroup',
            field=models.CharField(blank=True, max_length=56, null=True),
        ),
        migrations.AlterField(
            model_name='historicalseqdata',
            name='sistr_serovar_serovar',
            field=models.CharField(blank=True, max_length=56, null=True),
        ),
        migrations.AlterField(
            model_name='historicalseqdata',
            name='sixteens_result',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='historicalseqdata',
            name='total_length',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historicalseqdata',
            name='total_predicted_genes',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historicalseqdata',
            name='vtyper_profile',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='historicalseqtracking',
            name='comment',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='historicalseqtracking',
            name='curator_flag',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='historicalseqtracking',
            name='priority',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='lstsdata',
            name='country_of_origin',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='lstsdata',
            name='food',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='lstsidlist',
            name='lstsid_list',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=256, null=True), size=None),
        ),
        migrations.AlterField(
            model_name='oln',
            name='extra_lsts_data',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='oln',
            name='oln_genus',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='oln',
            name='oln_id',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='oln',
            name='oln_serotype',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='oln',
            name='oln_source',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='oln',
            name='oln_species',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='oln',
            name='oln_subspecies',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='oln',
            name='oln_verotoxin',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='oln',
            name='oneenzyme',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='oln',
            name='other_id',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='oln',
            name='twoenzyme',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='olnidlist',
            name='olnid_list',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=256, null=True), size=None),
        ),
        migrations.AlterField(
            model_name='resfinderdata',
            name='resfinder_aa_identity',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='resfinderdata',
            name='resfinder_allele',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='resfinderdata',
            name='resfinder_contig',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='resfinderdata',
            name='resfinder_gene',
            field=models.CharField(blank=True, max_length=56, null=True),
        ),
        migrations.AlterField(
            model_name='resfinderdata',
            name='resfinder_location',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='resfinderdata',
            name='resfinder_percent_covered',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='resfinderdata',
            name='resfinder_percent_identity',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='resfinderdata',
            name='resfinder_resistance',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='resfinderdata',
            name='resfinder_sequence',
            field=models.CharField(blank=True, max_length=8192, null=True),
        ),
        migrations.AlterField(
            model_name='savedqueries',
            name='query_name',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='savedtables',
            name='table_attributes',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=128, null=True), size=None),
        ),
        migrations.AlterField(
            model_name='savedtables',
            name='table_name',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='seqdata',
            name='amr_profile',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='seqdata',
            name='amr_resistant',
            field=models.CharField(blank=True, max_length=56, null=True),
        ),
        migrations.AlterField(
            model_name='seqdata',
            name='analyst',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='seqdata',
            name='assembly_quality',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='seqdata',
            name='average_coverage_depth',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='seqdata',
            name='core_genes_present',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='seqdata',
            name='coverage_depth_std',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='seqdata',
            name='date_assembled',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='seqdata',
            name='ecoli_serotype',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='seqdata',
            name='error_rate',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='seqdata',
            name='flowcell',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='seqdata',
            name='geneseekr_profile',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='seqdata',
            name='genus',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='seqdata',
            name='insert_size_std',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='seqdata',
            name='length_forward_read',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='seqdata',
            name='length_reverse_read',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='seqdata',
            name='machine_name',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='seqdata',
            name='mash_num_matching_hashes',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='seqdata',
            name='mash_reference_genome',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='seqdata',
            name='mean_insert_size',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='seqdata',
            name='mlst',
            field=models.CharField(blank=True, max_length=56, null=True),
        ),
        migrations.AlterField(
            model_name='seqdata',
            name='mlst_allele_1',
            field=models.CharField(blank=True, max_length=56, null=True),
        ),
        migrations.AlterField(
            model_name='seqdata',
            name='mlst_allele_2',
            field=models.CharField(blank=True, max_length=56, null=True),
        ),
        migrations.AlterField(
            model_name='seqdata',
            name='mlst_allele_3',
            field=models.CharField(blank=True, max_length=56, null=True),
        ),
        migrations.AlterField(
            model_name='seqdata',
            name='mlst_allele_4',
            field=models.CharField(blank=True, max_length=56, null=True),
        ),
        migrations.AlterField(
            model_name='seqdata',
            name='mlst_allele_5',
            field=models.CharField(blank=True, max_length=56, null=True),
        ),
        migrations.AlterField(
            model_name='seqdata',
            name='mlst_allele_6',
            field=models.CharField(blank=True, max_length=56, null=True),
        ),
        migrations.AlterField(
            model_name='seqdata',
            name='mlst_allele_7',
            field=models.CharField(blank=True, max_length=56, null=True),
        ),
        migrations.AlterField(
            model_name='seqdata',
            name='n50',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='seqdata',
            name='num_clusters_pf',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='seqdata',
            name='num_contigs',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='seqdata',
            name='percent_gc',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='seqdata',
            name='percent_reads_phix',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='seqdata',
            name='pipeline_version',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='seqdata',
            name='plasmid_profile',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='seqdata',
            name='predicted_genes_over_1000',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='seqdata',
            name='predicted_genes_over_3000',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='seqdata',
            name='predicted_genes_over_500',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='seqdata',
            name='predicted_genes_under_500',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='seqdata',
            name='real_time_strain',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='seqdata',
            name='rmlst',
            field=models.CharField(blank=True, max_length=56, null=True),
        ),
        migrations.AlterField(
            model_name='seqdata',
            name='sample_purity',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='seqdata',
            name='seqid',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='seqdata',
            name='sequencing_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='seqdata',
            name='sistr_serovar_antigen',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='seqdata',
            name='sistr_serovar_cgmlst',
            field=models.CharField(blank=True, max_length=56, null=True),
        ),
        migrations.AlterField(
            model_name='seqdata',
            name='sistr_serovar_h1',
            field=models.CharField(blank=True, max_length=56, null=True),
        ),
        migrations.AlterField(
            model_name='seqdata',
            name='sistr_serovar_h2',
            field=models.CharField(blank=True, max_length=56, null=True),
        ),
        migrations.AlterField(
            model_name='seqdata',
            name='sistr_serovar_serogroup',
            field=models.CharField(blank=True, max_length=56, null=True),
        ),
        migrations.AlterField(
            model_name='seqdata',
            name='sistr_serovar_serovar',
            field=models.CharField(blank=True, max_length=56, null=True),
        ),
        migrations.AlterField(
            model_name='seqdata',
            name='sixteens_result',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='seqdata',
            name='total_length',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='seqdata',
            name='total_predicted_genes',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='seqdata',
            name='vtyper_profile',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='seqidlist',
            name='seqid_list',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=256, null=True), size=None),
        ),
        migrations.AlterField(
            model_name='seqtracking',
            name='comment',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='seqtracking',
            name='curator_flag',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='seqtracking',
            name='priority',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
