# Generated by Django 2.0.4 on 2018-04-26 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_wrapper', '0004_seqidlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalseqdata',
            name='date_assembled',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='historicalseqdata',
            name='sequencing_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='seqdata',
            name='date_assembled',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='seqdata',
            name='sequencing_date',
            field=models.DateField(),
        ),
    ]
