# Generated by Django 2.0.4 on 2018-04-27 17:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('data_wrapper', '0005_auto_20180426_1922'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalSeqTracking',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('location', models.CharField(max_length=128)),
                ('oln_id', models.CharField(max_length=128)),
                ('project', models.CharField(max_length=128)),
                ('priority', models.CharField(max_length=128)),
                ('curator_flag', models.CharField(max_length=128)),
                ('comment', models.CharField(max_length=512)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('lsts_id', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='data_wrapper.LSTSData')),
                ('seqid', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='data_wrapper.Sample')),
            ],
            options={
                'verbose_name': 'historical seq tracking',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
        ),
        migrations.CreateModel(
            name='SeqTracking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=128)),
                ('oln_id', models.CharField(max_length=128)),
                ('project', models.CharField(max_length=128)),
                ('priority', models.CharField(max_length=128)),
                ('curator_flag', models.CharField(max_length=128)),
                ('comment', models.CharField(max_length=512)),
                ('lsts_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seq_tracking', to='data_wrapper.LSTSData')),
                ('seqid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seq_tracking', to='data_wrapper.Sample')),
            ],
        ),
    ]
