# Generated by Django 2.0.4 on 2018-04-27 20:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data_wrapper', '0006_historicalseqtracking_seqtracking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seqtracking',
            name='lsts_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seq_tracking_lstsid', to='data_wrapper.LSTSData'),
        ),
        migrations.AlterField(
            model_name='seqtracking',
            name='seqid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seq_tracking_seqid', to='data_wrapper.Sample'),
        ),
    ]
